sudo: required
services:
  - docker

before_install:
  - docker build -t praveentala/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true praveentala/docker-react npm run test -- --coverage


